### ISSUE TITLE
Fail to get an obfuscated string from a source data

### ISSUE THREAD

**Issue by atingchen** [cyrildever/feistel#4]
## My Test Code
```Go
	source := "my-source-data"
	cipher := feistel.NewFPECipher(hash.SHA_256, "some-32-byte-long-key-to-be-safe", 128)

	obfuscated, err := cipher.Encrypt(source)
	assert.NoError(t, err)
	str := obfuscated.String()
	fmt.Println(str)
	assert.Equal(t, len(source), len(str))
```
## My Result
```Shell
        	Error:      	Not equal: 
        	            	expected: 21
        	            	actual  : 14
        	Test:       	TestFormatPreservingEncryption
```
## My OS
MacOS 12.6 M1 

## Version
```GO 
github.com/cyrildever/feistel v1.3.21
```

**Comment by atingchen** [comment]
Do you have time to look at this issue? @cyrildever

**Comment by cyrildever** [comment]
As weird as it seems, it's actually normal... in a sense 😄 

Nevertheless, I've pushed a new version (`v1.4.0`) to fix the documentation and, above all, to offer a functionality that helps getting this behavior if need be with an extra optional argument to the `String()` method which, when set to `true`, returns the ASCII string which will reflect the equality in the test. (See #5)

```golang
source := "my-source-data"
cipher := feistel.NewFPECipher(hash.SHA_256, "some-32-byte-long-key-to-be-safe", 128)

obfuscated, _ := cipher.Encrypt(source)
str := obfuscated.String(true) // Notice the new argument here
assert.Equal(t, len(source), len(str))
```

You should read the new documentation, but as I say, it's normal and it's due to the way the `len()` function works in Go. It doesn't actually count the number of characters of a string, but the length of the underlying byte slice. In the (frequent) case where the obfuscated string uses characters encoded in more than one byte, then the result of the test I've shown in my documentation would be `false`. My mistake was to write that test in my documentation without even having testing the result, having forgotten the behavior of the `len()` function at the time. Sorry for that.
As I state in the new `README`, you should write the results using bytes directly, ie. the `Bytes()` method, not the `String()` which is not strict enough in the computer sense of the term.

_FYI: I decided not to make a new major version of this behavior (and not to change the default behavior of the `String()` method) because IMO it's still the correct one; therefore, the addition of the ASCII argument to the `String()` method should be of last resort because the way I built this library is to offer something that is **visibly** of the same number of characters, which means that it uses readable characters, hence the result type as `Base256Readable` and not plain string._

**Comment by atingchen** [comment]
Thank you
