### ISSUE TITLE
Some Doubts About Format-Preserving Encryption

### ISSUE THREAD

**Issue by atingchen** [cyrildever/feistel#6]
Wikipedia's definition of FPE as: 
> In [cryptography](https://en.wikipedia.org/wiki/Cryptography), format-preserving encryption (FPE), refers to encrypting in such a way that the output (the [ciphertext](https://en.wikipedia.org/wiki/Ciphertext)) is in the same format as the input (the [plaintext](https://en.wikipedia.org/wiki/Plaintext)). The meaning of "format" varies. Typically only finite sets of characters are used; numeric, alphabetic or alphanumeric. For example:
> - Encrypting a 16-digit credit card number so that the ciphertext is another 16-digit number.
> - Encrypting an English word so that the ciphertext is another English word.
> - Encrypting an n-bit number so that the ciphertext is another n-bit number (this is the definition of an n-bit block cipher).

However, the result obtained by encrypting the original data with Encrypt() does not seem to be in the same format as the original data.
For example, the encrypted number `123123123123`, according to `FPE`, what I get should be a string of pure numbers, but what I actually get is `ZW±ªX^²[[®R.
Did we just keep the same length?

**Comment by atingchen** [comment]
@cyrildever I hope you can answer this question when you have time.Thank you.

**Comment by cyrildever** [comment]
You're totally right: the tool was first thought as a string manipulation library, hence the `Encrypt()` method taking only strings as argument. So the length was indeed the main purpose, as well as the fact that it should return _visible_ latin characters (which is why I used my base-256 charset).
Moreover, it doesn't take into account the type of the incoming data.
So, it's well-suited for texts or pure byte arrays but not for other purposes.
Therefore, it's not a global FPE cipher per se, or in other words it encompasses only a small subset of the possible meanings of the "format" word, being more focused on text files or stdout without taking into account any context (such as if it were a credit card number for example) as I state in the introduction to my white papers.

I'm working on a little enhancement to take into account the other major type, ie. numbers and more specifically integers.
That way, you may use it to construct whatever output you may need. Refering to the credit card number example, it would mean to encrypt each group of four figures to a `EncryptNumber()` method and then rebuild the new number with the appropriate spaces, or pass the whole 16 figures as an integer to it.
It's still work in progress but you can see my endeavour in #7.

BTW, thanks for your feedback. It's always good to be challenged.

**Comment by atingchen** [comment]
@cyrildever Thank you very much for your work.

**Comment by cyrildever** [comment]
I've pushed the new evolution. As I said, it's not perfect, but it can be used to move towards actual FPE with the meaning of F being more strict.
